'use client';
import { useState } from 'react';
import { createRewardCatalogItem, createRewardRule } from '@/app/actions/rewards';

export function RewardAdmin({ catalog }: { catalog: any[] }) {
  const [catalogResult, setCatalogResult] = useState<any>(null);
  const [ruleResult, setRuleResult] = useState<any>(null);
  return <section className="mt-5 grid gap-5 xl:grid-cols-2">
    <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-bold">Add reward</h2><p className="mt-1 text-xs text-slate-500">Keep rewards small, useful and within a defined company budget.</p><form action={async (fd) => setCatalogResult(await createRewardCatalogItem(fd))} className="mt-4 space-y-3"><input name="name" required className="input" placeholder="2 Samosa / Cold Drink"/><textarea name="description" className="input resize-none" rows={2} placeholder="What the employee can redeem"/><div className="grid gap-3 sm:grid-cols-2"><input name="cost_inr" required type="number" min="0" step="1" className="input" placeholder="Budget value ₹"/><input name="stock_remaining" type="number" min="0" step="1" className="input" placeholder="Stock (blank = unlimited)"/></div><button className="rounded-xl bg-[var(--navy)] px-4 py-2.5 text-xs font-semibold text-white">Add reward</button>{catalogResult && <p className={`text-xs font-semibold ${catalogResult.error ? 'text-red-600' : 'text-emerald-600'}`}>{catalogResult.error ?? 'Reward added.'}</p>}</form></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-bold">Create reward rule</h2><p className="mt-1 text-xs text-slate-500">Attach an XP amount and optional physical reward to a meaningful event.</p><form action={async (fd) => setRuleResult(await createRewardRule(fd))} className="mt-4 space-y-3"><input name="name" required className="input" placeholder="Meeting completed → refreshment"/><div className="grid gap-3 sm:grid-cols-2"><select name="trigger_type" className="input"><option value="TASK_COMPLETED">Task completed</option><option value="VISIT_COMPLETED">Visit completed</option><option value="DAILY_GOAL">Daily goal</option><option value="WEEKLY_GOAL">Weekly goal</option><option value="STREAK">Streak</option></select><select name="task_type" className="input"><option value="">Any task type</option><option value="MEETING">Meeting</option><option value="CALL">Call</option><option value="FOLLOW_UP">Follow-up</option><option value="DEMO">Demo</option><option value="PROPOSAL">Proposal</option><option value="VISIT">Visit</option></select></div><div className="grid gap-3 sm:grid-cols-2"><select name="reward_id" className="input"><option value="">XP only</option>{catalog.map((r) => <option key={r.id} value={r.id}>{r.name} · ₹{Number(r.cost_inr).toLocaleString('en-IN')}</option>)}</select><input name="xp_amount" required type="number" min="0" step="5" defaultValue="50" className="input" placeholder="XP"/></div><input name="priority" type="number" min="0" step="1" defaultValue="100" className="input" placeholder="Priority (lower wins)"/><button className="rounded-xl bg-[var(--teal)] px-4 py-2.5 text-xs font-bold text-[var(--navy)]">Save rule</button>{ruleResult && <p className={`text-xs font-semibold ${ruleResult.error ? 'text-red-600' : 'text-emerald-600'}`}>{ruleResult.error ?? 'Rule added.'}</p>}</form></div>
  </section>;
}
