"use client";

import Link from "next/link";
import { Icon } from "@/components/icon";
import type { AppRole } from "@/lib/auth/types";
import type { DashboardData } from "@/lib/dashboard/queries";

const money = (value: number) => value >= 100000 ? `₹${(value / 100000).toFixed(value >= 1000000 ? 1 : 2)}L` : value >= 1000 ? `₹${(value / 1000).toFixed(1)}K` : `₹${Math.round(value).toLocaleString("en-IN")}`;
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "No due date";

function StatCard({ label, value, helper, icon, tone = "slate" }: { label: string; value: string; helper: string; icon: string; tone?: string }) {
  const toneClass = tone === "teal" ? "bg-teal-50 text-teal-700" : tone === "blue" ? "bg-blue-50 text-blue-700" : tone === "violet" ? "bg-violet-50 text-violet-700" : "bg-slate-50 text-slate-600";
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-2 text-[11px] text-slate-500">{helper}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${toneClass}`}><Icon name={icon} size={18} /></div></div></div>;
}

function Performance({ values }: { values: DashboardData["performance"] }) {
  const max = Math.max(...values.map((item) => item.value), 1);
  const points = values.map((item, index) => `${(index / Math.max(values.length - 1, 1)) * 100},${100 - (item.value / max) * 82 - 8}`).join(" ");
  return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-bold text-slate-950">Revenue performance</h2><p className="mt-1 text-xs text-slate-500">Won revenue · last 12 weeks</p></div><Link href="/leads" className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50">Open pipeline</Link></div><div className="mt-5 h-56 rounded-xl bg-slate-50/70 px-3 pt-3"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full" aria-label="Revenue performance chart" role="img"><line x1="0" x2="100" y1="25" y2="25" stroke="#e2e8f0" strokeWidth="0.35"/><line x1="0" x2="100" y1="50" y2="50" stroke="#e2e8f0" strokeWidth="0.35"/><line x1="0" x2="100" y1="75" y2="75" stroke="#e2e8f0" strokeWidth="0.35"/><polyline points={points} fill="none" stroke="#14b8a6" strokeWidth="1.5" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/>{values.map((item,index)=><circle key={item.label} cx={(index/Math.max(values.length-1,1))*100} cy={100-(item.value/max)*82-8} r="1.15" fill="white" stroke="#14b8a6" strokeWidth="0.7" vectorEffect="non-scaling-stroke"/>)}</svg></div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>{values[0]?.label}</span><span>{values[Math.floor(values.length/2)]?.label}</span><span>{values[values.length-1]?.label}</span></div></div>;
}

function TeamActivity({ team }: { team: DashboardData["team"] }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-950">Team activity</h2><p className="mt-1 text-xs text-slate-500">Current field-work state</p></div><Link href="/map" className="text-xs font-semibold text-teal-700">Open live map</Link></div><div className="mt-4 space-y-2.5">{team.slice(0,6).map((person)=><div key={person.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-900 text-[10px] font-bold text-white">{person.name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-800">{person.name}</p><p className="mt-0.5 truncate text-[10px] text-slate-500">{person.customer ? `On visit · ${person.customer}` : person.role.replaceAll("_", " ")}</p></div><span className={`flex items-center gap-1.5 text-[10px] font-semibold ${person.state === "Offline" ? "text-slate-400" : person.state === "On visit" ? "text-teal-700" : "text-blue-700"}`}><span className={`h-1.5 w-1.5 rounded-full ${person.state === "Offline" ? "bg-slate-300" : person.state === "On visit" ? "bg-teal-500" : "bg-blue-500"}`}/>{person.state}</span></div>)}</div></div>;
}

function Tasks({ tasks }: { tasks: DashboardData["tasks"] }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-950">Today&apos;s work</h2><p className="mt-1 text-xs text-slate-500">Priority actions across your scope</p></div><Link href="/field" className="text-xs font-semibold text-teal-700">View work</Link></div><div className="mt-4 space-y-2.5">{tasks.length ? tasks.map((task)=><div key={task.id} className="flex gap-3 rounded-xl border border-slate-100 p-3"><div className="mt-1 h-4 w-4 shrink-0 rounded-full border-2 border-slate-300"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-800">{task.title}</p><p className="mt-1 text-[10px] text-slate-500">{task.customer ? `${task.customer} · ` : ""}{dateLabel(task.due_at)}</p></div><span className={`self-start rounded-full px-2 py-1 text-[10px] font-semibold ${task.priority === "HIGH" ? "bg-red-50 text-red-600" : "bg-slate-100 text-slate-600"}`}>{task.priority}</span></div>) : <p className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">No tasks in the current queue.</p>}</div></div>;
}

function Leads({ leads }: { leads: DashboardData["leads"] }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-950">Recent leads</h2><p className="mt-1 text-xs text-slate-500">Latest CRM movement</p></div><Link href="/leads" className="text-xs font-semibold text-teal-700">View pipeline</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[460px] text-left"><thead><tr className="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400"><th className="pb-3 font-semibold">Lead</th><th className="pb-3 font-semibold">Owner</th><th className="pb-3 font-semibold">Stage</th><th className="pb-3 text-right font-semibold">Value</th></tr></thead><tbody>{leads.map((lead)=><tr key={lead.id} className="border-b border-slate-50 last:border-0"><td className="py-3"><div className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-slate-100 text-[9px] font-bold text-slate-600">{lead.title.slice(0,2).toUpperCase()}</span><span className="max-w-36 truncate text-xs font-semibold text-slate-800">{lead.title}</span></div></td><td className="py-3 text-xs text-slate-500">{lead.owner ?? "Unassigned"}</td><td className="py-3"><span className="rounded-full bg-teal-50 px-2 py-1 text-[10px] font-semibold text-teal-700">{lead.stage ?? "—"}</span></td><td className="py-3 text-right text-xs font-bold text-slate-800">{money(lead.value)}</td></tr>)}</tbody></table></div></div>;
}

export function Dashboard({ data, role, name }: { data: DashboardData; role: AppRole; name: string }) {
  const management = ["SUPER_ADMIN", "COMPANY_ADMIN", "SALES_MANAGER", "HR_ACCOUNTS"].includes(role);
  return <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">{new Intl.DateTimeFormat("en-IN", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Good morning, {name.split(" ")[0]}</h1><p className="mt-1 text-sm text-slate-500">{management ? "Here’s the clearest view of what needs attention across your sales operation." : "Here’s what needs your attention today."}</p></div><div className="flex gap-2"><Link href="/leads" className="flex items-center gap-2 rounded-xl bg-[var(--navy)] px-3.5 py-2.5 text-xs font-semibold text-white shadow-sm hover:bg-[var(--navy-2)]"><Icon name="plus" size={15}/> New lead</Link></div></div><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label={management ? "Sales this month" : "Your sales this month"} value={money(data.kpis.sales)} helper="Won revenue" icon="bar-chart" tone="teal"/><StatCard label="Qualified leads" value={String(data.kpis.qualifiedLeads)} helper="Current CRM scope" icon="users"/><StatCard label="Visits completed" value={String(data.kpis.visits)} helper="This month" icon="map-pin" tone="blue"/><StatCard label="Open pipeline" value={money(data.kpis.pipeline)} helper={`${data.pendingExpenses.count} expense${data.pendingExpenses.count === 1 ? "" : "s"} pending`} icon="chart-no-axes-combined" tone="violet"/></section><section className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_1fr]"><Performance values={data.performance}/><TeamActivity team={data.team}/></section><section className="mt-4 grid gap-4 xl:grid-cols-[0.9fr_1.35fr]"><Tasks tasks={data.tasks}/><Leads leads={data.leads}/></section></main>;
}
