"use client";

import {
  BarChart3,
  Bell,
  BellOff,
  Building2,
  CalendarCheck,
  ChartNoAxesCombined,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  CircleHelp,
  Clock,
  CupSoda,
  Download,
  FileBarChart,
  Filter,
  Flame,
  Gift,
  LayoutDashboard,
  LogOut,
  Map,
  MapPin,
  MapPinCheck,
  Menu,
  Percent,
  Plus,
  Receipt,
  Route,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  TrendingUp,
  Trophy,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  X,
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "check-square": CheckSquare,
  users: Users,
  "users-round": UsersRound,
  "building-2": Building2,
  "map-pin": MapPin,
  "map-pin-check": MapPinCheck,
  map: Map,
  route: Route,
  receipt: Receipt,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "file-bar-chart": FileBarChart,
  search: Search,
  bell: Bell,
  "bell-off": BellOff,
  plus: Plus,
  settings: Settings,
  "circle-help": CircleHelp,
  "user-round": UserRound,
  "chevron-down": ChevronDown,
  "shield-check": ShieldCheck,
  "bar-chart": BarChart3,
  "sliders-horizontal": SlidersHorizontal,
  menu: Menu,
  x: X,
  "log-out": LogOut,
  wallet: Wallet,
  "badge-dollar-sign": BadgeDollarSign,
  "badge-check": BadgeCheck,
  percent: Percent,
  banknote: Banknote,
  gift: Gift,
  "calendar-check": CalendarCheck,
  download: Download,
  funnel: Filter,
  filter: Filter,
  "cup-soda": CupSoda,
  flame: Flame,
  trophy: Trophy,
  "trending-up": TrendingUp,
  clock: Clock,
  "check-circle-2": CheckCircle2,
};

export function Icon({ name, size = 18, strokeWidth = 1.8, className }: { name: string; size?: number; strokeWidth?: number; className?: string }) {
  const Component = icons[name] ?? CircleHelp;
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
